### ISSUE TITLE
Question: Is Symfony required?

### ISSUE THREAD

**Issue by mimmi20** [actived/microsoft-teams-notifier#2]
I would like to use this Package, but we use Laminas. I did not find the file in this Package where Symfony is required.

Is it possible to remove this dependency? Or change to a Dev-dependency?

**Comment by actived** [comment]
Hi @mimmi20,
thank you for taking time with the code and your question. 

The package uses 'symfony/monolog-bundle'. I am not sure what is required on your side.
`Is it possible to remove this dependency? Or change to a Dev-dependency?`  Which dependency should be removed? What is yours that raises notification in your app?
If you would like to add one, please give us more details about imlementation.

Many thanks,

Actived Team

**Comment by mimmi20** [comment]
Hello @actived,

In our company, we dont use Symfony. The used bundle is an issue for us, as it adds a lot stuff we dont need.

I looked into the code of this package, but I did not find anything where symfony was used inside this package. May be I did not see that piece of code.

Actually we want to use the package `cmdisp/monolog-microsoft-teams`, but their message is not well formatted.

With kind regards 

mimmi20

**Comment by actived** [comment]
Hi @mimmi20, we have updated dependencies and replaced "symfony/monolog-bundle" by "monolog/monolog": "^1.22|^2.0".

Could you please confiorm if it work for you?

Once we get the confirmation we will run additional tests and update documentation for Symfony users - they would need to install 'symfony/monolog-bundle' additional dependency to make the things work.

Thanks,

Actived Team

**Comment by mimmi20** [comment]
Hello @actived,

it works now for us. 

You may add the "symfony/monolog-bundle" package into the ["suggest"](https://getcomposer.org/doc/04-schema.md#suggest) area in the composer.json.

Thanks

mimmi20

**Comment by actived** [comment]
This is what we planned to do. 

If there is anything we can do, please let us know.

Thanks,

Actived Team
